### ISSUE TITLE
bug: the Notification could not be delivered due to an unknown error

### ISSUE THREAD

**Issue by jonz94** [jonz94/capacitor-azure-notification-hubs#10]
### Discussed in https://github.com/jonz94/capacitor-azure-notification-hubs/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **rumaisaknaz** May  2, 2024</sup>
After Setting azureNotificationHubsVersion = '2.0.0' and releasing the app, on update of the current app, the registration with Azure Notification hub is not happening properly and on test send it shows The Notification could not be delivered due to an unknown error</div>

**Comment by rumaisaknaz** [comment]
You can close this issue, it was due to our DeviceTag setup. When using the same devicetag as before as `${identifier}` notifications delivery was not happening for android. After updating the devicetag to `${identifier}-v1` or appending something to it, it worked

```
const { identifier } = await Device.getId();
const myDeviceTag = `${identifier}`
```
