### ISSUE TITLE
Error on iOS (setup push channel)

### ISSUE THREAD

**Issue by asieverding** [jonz94/capacitor-azure-notification-hubs#4]
Hello, push notifications are working on Android but not on iOS for me. I have implemented the plugin as mentioned in the documentation. When I register the plugin for iOS I get the following error:

```
2023-09-12 16:26:53.765769+0200 App[10917:116230] Push notifications authorization was granted.
⚡️  To Native ->  AzureNotificationHubs addListener 125145408
⚡️  To Native ->  AzureNotificationHubs addListener 125145409
2023-09-12 16:26:55.753247+0200 App[10917:116007] Error while creating installation: The operation couldn’t be completed. (WindowsAzureMessaging error -1.)
{
    Error = "You have to setup Push Channel before save installation";
}
```

**Comment by Tramb-dev** [comment]
Hello, I have set up registration with iOS and Android successfully with this plugin. There is a step that is not mentioned in the readme from this plugin or from capacitor. You need to enable push notifications for your iOS app in the Apple Developer portal. Generate an APNs (Apple Push Notification service) certificate or key and configure your app to use it. Then configure Azure Notification Hub with the certificate / token used by the Apple Push Notification service.

Hope it helps.

**Comment by asieverding** [comment]
I have all that set up. I have now installed the app on my iPhone and there the notifications work. In the emulator they do not work, there I get the above error message. Since it works on the iPhone the issue is resolved for me.
