### ISSUE TITLE
Add Google FCM v1 Support

### ISSUE THREAD

**Issue by asieverding** [jonz94/capacitor-azure-notification-hubs#5]
Azure Notification Hubs Support for GCM/FCM Legacy will be retired by 1 July 2024.
Therefore a migration to FCM v1 is required until the deadline.
Can you update this plugin to use FCM v1?

<https://learn.microsoft.com/en-us/azure/notification-hubs/notification-hubs-gcm-to-fcm>

**Comment by asieverding** [comment]
I was able to solve the problem with the current version by setting azureNotificationHubsVersion = '2.0.0'.

**Comment by jonz94** [comment]
Hi Andre,

Thanks for the information!

If you encounter any issues using the `azureNotificationHubsVersion = '2.0.0'` setting alongside this plugin,
feel free to open another issue!
